<?php

declare(strict_types=1);

namespace App\Ai\Tools;

use App\Enums\AllergySeverity;
use App\Enums\UserProfileAttributeCategory;
use App\Models\User;
use App\Models\UserProfileAttribute;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Illuminate\Support\Facades\Auth;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Tools\Request;

final readonly class UpdateUserProfileAttributes implements Tool
{
    public function name(): string
    {
        return 'update_user_profile_attributes';
    }

    public function description(): string
    {
        return 'Add, update, or remove user profile attributes such as dietary preferences (allergies, intolerances, dietary patterns, dislikes, restrictions), health conditions, and medications. Use this when the user mentions having allergies, dietary restrictions, health conditions, or medications during conversation. Use "list" to see current attributes before making changes. For "add" and "update" actions, provide metadata generated by the enrich_attribute_metadata tool.';
    }

    public function handle(Request $request): string
    {
        $user = Auth::user();

        if (! $user instanceof User) {
            return (string) json_encode(['error' => 'User not authenticated']);
        }

        $profile = $user->profile()->firstOrCreate(['user_id' => $user->id]);

        /** @var array<string, mixed> $data */
        $data = $request->toArray();

        /** @var string $action */
        $action = $data['action'] ?? 'list';

        return match ($action) {
            'list' => $this->listAttributes($profile->id),
            'add' => $this->addAttribute($profile->id, $data),
            'update' => $this->updateAttribute($profile->id, $data),
            'remove' => $this->removeAttribute($profile->id, $data),
            default => (string) json_encode(['error' => 'Unknown action: '.$action]),
        };
    }

    /**
     * @return array<string, mixed>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'action' => $schema->string()->required()
                ->enum(['list', 'add', 'update', 'remove'])
                ->description('Action to perform: "list" to see current attributes, "add" to add a new one, "update" to modify an existing one, "remove" to delete one.'),
            'category' => $schema->string()->required()->nullable()
                ->enum(UserProfileAttributeCategory::class)
                ->description('Category of the attribute. Required for add/update/remove.'),
            'value' => $schema->string()->required()->nullable()
                ->description('The attribute value (e.g., "Peanuts", "Type 2 Diabetes", "Vegan", "Metformin"). Required for add/update/remove.'),
            'severity' => $schema->string()->required()->nullable()
                ->enum(AllergySeverity::class)
                ->description('Severity level for allergies only: mild, moderate, severe.'),
            'notes' => $schema->string()->required()->nullable()
                ->description('Additional notes about this attribute.'),
            'metadata' => $schema->object(fn (JsonSchema $s): array => [
                'dosage' => $s->string()->required()->nullable()->description('Medication dosage (e.g., "500mg").'),
                'frequency' => $s->string()->required()->nullable()->description('Medication frequency (e.g., "twice daily").'),
                'purpose' => $s->string()->required()->nullable()->description('Purpose of the medication (e.g., "Blood sugar control").'),
                'safety_level' => $s->string()->required()->nullable()->description('Safety level from enrich_attribute_metadata tool.'),
                'dietary_rules' => $s->string()->required()->nullable()->description('Dietary rules from enrich_attribute_metadata tool.'),
                'foods_to_avoid' => $s->string()->required()->nullable()->description('Foods to avoid from enrich_attribute_metadata tool.'),
            ])->withoutAdditionalProperties()->required()->nullable()
                ->description('Structured metadata from enrich_attribute_metadata tool or medication details.'),
        ];
    }

    private function listAttributes(int $profileId): string
    {
        $attributes = UserProfileAttribute::query()
            ->where('user_profile_id', $profileId)
            ->orderBy('category')
            ->orderBy('value')
            ->get();

        if ($attributes->isEmpty()) {
            return (string) json_encode([
                'success' => true,
                'message' => 'No profile attributes found. The user has not set any dietary preferences, health conditions, or medications.',
                'attributes' => [],
            ]);
        }

        return (string) json_encode([
            'success' => true,
            'attributes' => $attributes->map(fn (UserProfileAttribute $attr): array => $this->formatAttribute($attr))->values()->all(),
        ]);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function addAttribute(int $profileId, array $data): string
    {
        /** @var string|null $categoryValue */
        $categoryValue = $data['category'] ?? null;

        /** @var string|null $value */
        $value = $data['value'] ?? null;

        if (! $categoryValue || ! $value) {
            return (string) json_encode(['error' => 'Both "category" and "value" are required to add an attribute.']);
        }

        $category = UserProfileAttributeCategory::tryFrom($categoryValue);

        if (! $category) {
            return (string) json_encode(['error' => 'Invalid category: '.$categoryValue]);
        }

        /** @var string|null $severityValue */
        $severityValue = $data['severity'] ?? null;
        $severity = $severityValue ? AllergySeverity::tryFrom($severityValue) : null;

        /** @var string|null $notes */
        $notes = $data['notes'] ?? null;

        /** @var array<string, mixed>|null $metadata */
        $metadata = $data['metadata'] ?? null;

        $attribute = UserProfileAttribute::query()->updateOrCreate(
            [
                'user_profile_id' => $profileId,
                'category' => $category,
                'value' => $value,
            ],
            [
                'severity' => $severity,
                'notes' => $notes,
                'metadata' => $metadata !== [] ? $metadata : null,
            ],
        );

        return (string) json_encode([
            'success' => true,
            'message' => sprintf('Added %s: %s', $category->label(), $value),
            'attribute' => $this->formatAttribute($attribute),
        ]);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function updateAttribute(int $profileId, array $data): string
    {
        /** @var string|null $categoryValue */
        $categoryValue = $data['category'] ?? null;

        /** @var string|null $value */
        $value = $data['value'] ?? null;

        if (! $categoryValue || ! $value) {
            return (string) json_encode(['error' => 'Both "category" and "value" are required to identify the attribute to update.']);
        }

        $attribute = UserProfileAttribute::query()
            ->where('user_profile_id', $profileId)
            ->where('category', $categoryValue)
            ->where('value', $value)
            ->first();

        if (! $attribute) {
            return (string) json_encode(['error' => sprintf('Attribute not found: %s - %s', $categoryValue, $value)]);
        }

        $updateData = [];

        if (isset($data['severity']) && is_string($data['severity'])) {
            $updateData['severity'] = AllergySeverity::tryFrom($data['severity']);
        }

        if (array_key_exists('notes', $data)) {
            $updateData['notes'] = is_string($data['notes']) ? $data['notes'] : null;
        }

        if (isset($data['metadata']) && is_array($data['metadata'])) {
            $updateData['metadata'] = $data['metadata'] !== [] ? $data['metadata'] : null;
        }

        if ($updateData !== []) {
            $attribute->update($updateData);
            $attribute->refresh();
        }

        return (string) json_encode([
            'success' => true,
            'message' => sprintf('Updated %s: %s', $attribute->category->label(), $attribute->value),
            'attribute' => $this->formatAttribute($attribute),
        ]);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function removeAttribute(int $profileId, array $data): string
    {
        /** @var string|null $categoryValue */
        $categoryValue = $data['category'] ?? null;

        /** @var string|null $value */
        $value = $data['value'] ?? null;

        if (! $categoryValue || ! $value) {
            return (string) json_encode(['error' => 'Both "category" and "value" are required to remove an attribute.']);
        }

        $deleted = UserProfileAttribute::query()
            ->where('user_profile_id', $profileId)
            ->where('category', $categoryValue)
            ->where('value', $value)
            ->delete();

        if ($deleted === 0) {
            return (string) json_encode(['error' => sprintf('Attribute not found: %s - %s', $categoryValue, $value)]);
        }

        return (string) json_encode([
            'success' => true,
            'message' => sprintf('Removed %s from profile.', $value),
        ]);
    }

    /**
     * @return array<string, mixed>
     */
    private function formatAttribute(UserProfileAttribute $attribute): array
    {
        return [
            'id' => $attribute->id,
            'category' => $attribute->category->value,
            'value' => $attribute->value,
            'severity' => $attribute->severity?->value,
            'notes' => $attribute->notes,
            'metadata' => $attribute->metadata,
        ];
    }
}
